
### Categories
GET http://127.0.0.1:8000/api/categories

###
GET http://127.0.0.1:8000/api/list/categories

###
GET http://127.0.0.1:8000/api/categories/100


### Products

GET http://127.0.0.1:8000/api/products
